[jupiter.server.http]
	host = "127.0.0.1"
    port = 9900

[jupiter.logger.default]
    enableConsole = true
    level = "debug"
    debug = true
    MaxAge = 2
    MaxBackup = 10
    Dir = "./logs/"
    Async = false

[jupiter.mysql.master]
   connMaxLifetime = "300s"
   debug = true
   dsn = "root:123456@tcp(127.0.0.1:3306)/lightning-go?charset=utf8&parseTime=True&loc=Local&readTimeout=5s&timeout=5s&writeTimeout=3s"
   level = "panic"
   maxIdleConns = 50
   maxOpenConns = 100

[jupiter.mysql.airflow]
   connMaxLifetime = "300s"
   debug = true
   dsn = "root:123456@tcp(127.0.0.1:3306)/airflow?charset=utf8&parseTime=True&loc=Local&readTimeout=5s&timeout=5s&writeTimeout=3s"
   level = "panic"
   maxIdleConns = 50
   maxOpenConns = 100


[jupiter.cron.chaos]
	withSeconds = true
    immediatelyRun = false
    concurrentDelay = -1


[jupiter.server.governor]
   enable = false
   host = "0.0.0.0"
   port = 9800


[go-ops.hosts]
    auth = "http://121.4.224.236:8000/api/v1/has-perm"

[go-ops.scheduler]
    airflowUrl = "http://121.4.224.236:8888"
    airflowUserName = "admin"
    airflowUserPassword = "zhengyansheng"
